# Generated by Django 3.2.8 on 2021-10-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20211017_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_time',
            field=models.DateField(null=True, verbose_name='تاریخ تحویل'),
        ),
        migrations.AddField(
            model_name='order',
            name='prepayment',
            field=models.IntegerField(default=0, verbose_name='پیش پرداخت'),
        ),
        migrations.AddField(
            model_name='order',
            name='prepayment_time',
            field=models.DateField(null=True, verbose_name='تاریخ پیش پرداخت'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
